-- ---------------------------------------------------------------------
-- SAMPLE DATA (safe to re-run: existing rows are never overwritten)
-- All prices are illustrative. Edit or delete anything from Admin > Products.
-- ---------------------------------------------------------------------

insert into public.store_settings (
  id, business_name, tagline, phone, whatsapp, email, address, county, business_hours, about, payment_instructions,
  deposit_percent, delivery_mode, fixed_delivery_fee, default_delivery_fee, free_delivery_threshold,
  facebook_url, instagram_url
) values (
  1, 'BeiHub', 'Quality Products. Better Prices. Delivered.', '+254 700 000 000', '254700000000', 'hello@beihub.co.ke', 'Update your shop address in Admin > Settings', 'Nairobi',
  'Mon - Sat: 8:00am - 6:00pm', 'BeiHub is a Kenyan catalogue and order desk for electronics, appliances, water tanks and solar equipment. Browse prices, pick what you need and send your order list. We confirm every order personally.', 'After you submit your order we will call or WhatsApp you to confirm availability and delivery, and send our M-Pesa / bank details for the 50% deposit. The balance is paid when your order is delivered.', 50, 'county', 1500, 2500,
  null::numeric, null, null
) on conflict (id) do nothing;

insert into public.categories (name, slug, description, image_url, sort_order) values
  ('Water Tanks', 'water-tanks', 'Vertical and storage tanks from 100 to 24,000 litres, plus fittings.', '/sample-products/category-water-tanks.svg', 10),
  ('TVs & Entertainment', 'tvs-entertainment', 'Smart LED and 4K televisions in popular screen sizes.', '/sample-products/category-tvs-entertainment.svg', 20),
  ('Speakers & Sound Systems', 'speakers-sound', 'Bluetooth speakers, soundbars and home theatre systems.', '/sample-products/category-speakers-sound.svg', 30),
  ('Refrigerators & Freezers', 'refrigerators-freezers', 'Single door, double door, side-by-side fridges and chest freezers.', '/sample-products/category-refrigerators-freezers.svg', 40),
  ('Home Appliances', 'home-appliances', 'Microwaves, washing machines and everyday home appliances.', '/sample-products/category-home-appliances.svg', 50),
  ('Computers & Laptops', 'computers-laptops', 'Laptops, desktop computers and monitors for home and office.', '/sample-products/category-computers-laptops.svg', 60),
  ('CCTV & Security', 'cctv-security', 'CCTV cameras, complete kits and DVR / NVR recorders.', '/sample-products/category-cctv-security.svg', 70),
  ('Networking & Wi-Fi', 'networking-wifi', 'Wi-Fi routers, network switches and access points.', '/sample-products/category-networking-wifi.svg', 80),
  ('Solar Equipment', 'solar-equipment', 'Solar panels, charge controllers, cables and accessories.', '/sample-products/category-solar-equipment.svg', 90),
  ('Inverters & Batteries', 'inverters-batteries', 'Hybrid inverters and deep-cycle solar batteries.', '/sample-products/category-inverters-batteries.svg', 100),
  ('Water Pumps', 'water-pumps', 'Surface, pressure booster and borehole submersible pumps.', '/sample-products/category-water-pumps.svg', 110),
  ('Power Equipment', 'power-equipment', 'Generators and voltage regulators for reliable power.', '/sample-products/category-power-equipment.svg', 120),
  ('Electronics', 'electronics', 'Power banks, earbuds and everyday electronics.', '/sample-products/category-electronics.svg', 130),
  ('Other Accessories', 'other-accessories', 'Extension sockets, wall mounts and handy accessories.', '/sample-products/category-other-accessories.svg', 140)
on conflict (slug) do nothing;

insert into public.delivery_locations (county, town, fee, eta, sort_order) values
  ('Nairobi', null, 1000, '1-2 days', 10),
  ('Nairobi', 'CBD', 600, 'Same or next day', 20),
  ('Kiambu', null, 1500, '1-2 days', 30),
  ('Machakos', null, 1800, '2-3 days', 40),
  ('Kajiado', null, 1800, '2-3 days', 50),
  ('Nakuru', null, 2500, '2-3 days', 60),
  ('Kisumu', null, 3200, '3-4 days', 70),
  ('Kakamega', null, 3500, '3-4 days', 80),
  ('Mombasa', null, 4500, '3-5 days', 90),
  ('Uasin Gishu', null, 3200, '3-4 days', 100)
on conflict do nothing;

insert into public.products (category_id, name, slug, brand, short_description, description, specs, is_featured, is_popular, is_new)
select c.id, v.name, v.slug, v.brand, v.short_description, v.description, v.specs, v.is_featured, v.is_popular, v.is_new
from (values
  ('water-tanks'::text, 'Water Tank'::text, 'water-tank'::text, null::text, 'Vertical food-grade polyethylene water tank with UV protection.'::text, 'A durable vertical water tank moulded from food-grade polyethylene with UV stabilisers, so water stays clean and the tank stands up to the Kenyan sun. Suitable for homes, farms, schools and commercial sites. Every tank has a screw lid and a 1-inch outlet boss for fittings.'::text, '{"Material":"Food-grade polyethylene (LLDPE)","UV protection":"Yes","Outlet":"1 inch","Lid":"Screw-on, lockable","Warranty":"5 years on the tank body"}'::jsonb, true, true, false),
  ('water-tanks'::text, 'Triple-Layer Water Tank'::text, 'triple-layer-water-tank'::text, null::text, 'Three-layer tank that blocks light to keep water fresher for longer.'::text, 'The black inner layer blocks sunlight to reduce algae growth, the middle layer adds strength and the outer layer resists UV. A good choice for drinking-water storage and for sites with strong sun.'::text, '{"Material":"Three-layer polyethylene","Light blocking":"Black inner layer","UV protection":"Yes","Outlet":"1 inch"}'::jsonb, false, false, true),
  ('water-tanks'::text, 'Tank Fittings Kit'::text, 'tank-fittings-kit'::text, null::text, 'Ball valve, float valve, unions and sockets to plumb your tank.'::text, 'Everything needed to connect a water tank: brass ball valve, float valve, tank connector, socket and elbow. Choose the pipe size that matches your plumbing.'::text, '{"Contents":"Ball valve, float valve, tank connector, socket, elbow","Material":"Brass and PVC"}'::jsonb, false, false, false),
  ('tvs-entertainment'::text, 'Samsung 4K UHD Smart TV'::text, 'samsung-4k-uhd-smart-tv'::text, 'Samsung'::text, '4K Ultra HD smart television with built-in streaming apps.'::text, 'Crisp 4K picture, built-in Wi-Fi and popular streaming apps ready to use. Includes remote control and wall-mount compatible back panel. Choose the screen size that suits your room.'::text, '{"Resolution":"3840 x 2160 (4K UHD)","Smart TV":"Yes, with streaming apps","Connectivity":"Wi-Fi, Bluetooth, 3 x HDMI, 1 x USB","Warranty":"1 year"}'::jsonb, true, true, false),
  ('tvs-entertainment'::text, 'LG UHD Smart TV'::text, 'lg-uhd-smart-tv'::text, 'LG'::text, 'UHD smart TV with webOS and voice-ready remote.'::text, 'UHD resolution, a fast processor and an easy-to-use smart interface. Slim bezel design for a clean look on a stand or on the wall.'::text, '{"Resolution":"3840 x 2160 (UHD)","Smart TV":"Yes","Connectivity":"Wi-Fi, Bluetooth, 3 x HDMI, 2 x USB","Warranty":"1 year"}'::jsonb, false, false, true),
  ('tvs-entertainment'::text, 'Hisense Full HD Smart TV'::text, 'hisense-full-hd-smart-tv'::text, 'Hisense'::text, 'Affordable Full HD smart TV for the bedroom or living room.'::text, 'A budget-friendly smart TV with Full HD picture, built-in Wi-Fi and streaming apps.'::text, '{"Resolution":"1920 x 1080 (Full HD)","Smart TV":"Yes","Connectivity":"Wi-Fi, 2 x HDMI, 1 x USB","Warranty":"1 year"}'::jsonb, false, true, false),
  ('speakers-sound'::text, 'Portable Bluetooth Speaker'::text, 'portable-bluetooth-speaker'::text, 'JBL'::text, 'Rechargeable wireless speaker with deep bass.'::text, 'Pair with your phone over Bluetooth and enjoy loud, clear sound at home, in the shop or outdoors. Rechargeable battery, USB charging and a carry strap.'::text, '{"Connectivity":"Bluetooth 5.0, AUX, USB","Battery":"Rechargeable lithium","Water resistance":"Splash resistant"}'::jsonb, false, true, false),
  ('speakers-sound'::text, 'Soundbar with Subwoofer'::text, 'soundbar-with-subwoofer'::text, 'LG'::text, 'Wireless subwoofer and soundbar to upgrade your TV sound.'::text, 'Connects to your TV by HDMI ARC, optical or Bluetooth. A wireless subwoofer adds punchy bass for movies, football and music.'::text, '{"Connectivity":"HDMI ARC, Optical, Bluetooth, USB","Subwoofer":"Wireless","Remote":"Included"}'::jsonb, false, true, false),
  ('speakers-sound'::text, 'Home Theatre System'::text, 'home-theatre-system'::text, 'Sony'::text, 'Surround sound system with tower speakers and AV receiver.'::text, 'Fill your living room with powerful surround sound. Includes tower speakers, centre speaker, subwoofer and receiver with HDMI and Bluetooth.'::text, '{"Connectivity":"HDMI, Optical, Bluetooth, USB","Includes":"Receiver, tower speakers, centre speaker, subwoofer"}'::jsonb, false, false, true),
  ('refrigerators-freezers'::text, 'Single Door Refrigerator'::text, 'single-door-refrigerator'::text, 'Ramtons'::text, 'Compact single door fridge with a small freezer compartment.'::text, 'A practical choice for bedsitters, offices and small families. Adjustable shelves, vegetable crisper and a built-in freezer compartment.'::text, '{"Type":"Direct cool, single door","Energy use":"Low consumption","Warranty":"1 year"}'::jsonb, false, true, false),
  ('refrigerators-freezers'::text, 'Double Door Refrigerator'::text, 'double-door-refrigerator'::text, 'Hisense'::text, 'Top-freezer double door fridge with a spacious fresh-food section.'::text, 'Frost-free cooling, separate freezer and fridge doors and a steel-look finish. Plenty of space for a family.'::text, '{"Type":"Frost free, top freezer","Finish":"Stainless-steel look","Warranty":"2 years"}'::jsonb, true, true, false),
  ('refrigerators-freezers'::text, 'Side-by-Side Refrigerator'::text, 'side-by-side-refrigerator'::text, 'LG'::text, 'Large side-by-side fridge-freezer with water dispenser.'::text, 'A large-capacity fridge-freezer with external water dispenser and digital temperature control. Built for big households and hospitality.'::text, '{"Type":"Frost free, side-by-side","Dispenser":"Water","Warranty":"2 years"}'::jsonb, false, false, true),
  ('refrigerators-freezers'::text, 'Chest Freezer'::text, 'chest-freezer'::text, 'Von'::text, 'Deep chest freezer for bulk storage of meat, fish and drinks.'::text, 'Strong cooling for shops, butcheries and homes. Lockable lid, removable basket and fast-freeze switch. Great value for bulk storage.'::text, '{"Type":"Chest, manual defrost","Lid":"Lockable","Warranty":"1 year"}'::jsonb, false, true, false),
  ('home-appliances'::text, 'Microwave Oven'::text, 'microwave-oven'::text, 'Ramtons'::text, 'Digital microwave with multiple power levels and defrost.'::text, 'Heat, cook and defrost quickly. Digital controls, multiple power levels and a easy-clean interior.'::text, '{"Control":"Digital","Functions":"Reheat, cook, defrost","Warranty":"1 year"}'::jsonb, false, false, false),
  ('home-appliances'::text, 'Front-Load Washing Machine'::text, 'front-load-washing-machine'::text, 'Hisense'::text, 'Energy-efficient front loader with multiple wash programmes.'::text, 'Inverter motor, quick wash and several programmes for different fabrics. Choose the drum capacity for your household.'::text, '{"Type":"Front load, fully automatic","Motor":"Inverter","Warranty":"2 years"}'::jsonb, false, false, false),
  ('computers-laptops'::text, 'Business Laptop 15.6 Inch'::text, 'business-laptop-15'::text, 'HP'::text, 'Reliable 15.6 inch laptop for work, school and business.'::text, 'Full HD display, fast SSD storage, backlit-ready keyboard and long battery life. Windows 11 ready. Choose the processor, memory and storage that fit your budget.'::text, '{"Display":"15.6 inch Full HD","Operating system":"Windows 11","Warranty":"1 year"}'::jsonb, true, true, false),
  ('computers-laptops'::text, 'Desktop Computer Set'::text, 'desktop-computer-set'::text, 'Dell'::text, 'Tower, monitor, keyboard and mouse - ready to plug in.'::text, 'A complete desktop set for the office, cyber or home. Includes tower, LED monitor, keyboard and mouse.'::text, '{"Includes":"Tower, monitor, keyboard, mouse","Operating system":"Windows 11","Warranty":"1 year"}'::jsonb, false, false, false),
  ('computers-laptops'::text, 'LED Monitor'::text, 'led-monitor'::text, 'Lenovo'::text, 'Slim-bezel LED monitor with HDMI input.'::text, 'A sharp, flicker-free display for work, CCTV viewing and entertainment. HDMI and VGA inputs, wall-mountable.'::text, '{"Panel":"IPS LED","Inputs":"HDMI, VGA","Refresh rate":"75Hz","Warranty":"1 year"}'::jsonb, false, false, false),
  ('cctv-security'::text, 'Outdoor CCTV Bullet Camera'::text, 'outdoor-cctv-bullet-camera'::text, 'Hikvision'::text, 'Weatherproof bullet camera with night vision.'::text, 'Metal housing, IP66 weather protection and infrared night vision up to 30 metres. Works with DVR/NVR recorders.'::text, '{"Weather rating":"IP66","Night vision":"Up to 30m","Housing":"Metal"}'::jsonb, false, true, false),
  ('cctv-security'::text, 'CCTV Camera Kit'::text, 'cctv-camera-kit'::text, 'Hikvision'::text, 'Complete kit: cameras, recorder, hard drive, cables and power supply.'::text, 'A complete security kit ready for installation. Includes cameras, DVR, hard drive, power supply and connectors. Installation can be arranged on request.'::text, '{"Includes":"Cameras, DVR, 1TB HDD, cables, power supply","Remote viewing":"Phone app"}'::jsonb, true, true, false),
  ('cctv-security'::text, 'DVR / NVR Recorder'::text, 'dvr-nvr-recorder'::text, 'Hikvision'::text, 'Digital video recorders for analogue and IP cameras.'::text, 'Record and play back CCTV footage with phone app viewing. Supports hard drives up to 8TB (hard drive sold separately).'::text, '{"Remote viewing":"Phone app","Hard drive":"Not included"}'::jsonb, false, false, false),
  ('networking-wifi'::text, 'Wi-Fi Router'::text, 'wifi-router'::text, 'TP-Link'::text, 'Dual-band Wi-Fi routers for home and office.'::text, 'Fast, stable Wi-Fi for streaming and video calls. Easy setup with a phone app. The 4G LTE model takes a SIM card so you can get internet without a fixed line.'::text, '{"Setup":"Phone app","Ports":"Gigabit LAN","Warranty":"1 year"}'::jsonb, false, true, true),
  ('networking-wifi'::text, 'Gigabit Network Switch'::text, 'network-switch'::text, 'TP-Link'::text, 'Plug-and-play gigabit switches for offices and CCTV.'::text, 'Expand your wired network with gigabit ports. No configuration needed. Metal case suitable for desk or rack mounting.'::text, '{"Speed":"10/100/1000 Mbps","Management":"Unmanaged","Warranty":"1 year"}'::jsonb, false, false, false),
  ('networking-wifi'::text, 'Wireless Access Point'::text, 'wireless-access-point'::text, 'Tenda'::text, 'Ceiling-mount and outdoor access points for wide Wi-Fi coverage.'::text, 'Extend Wi-Fi coverage in offices, hotels and schools. Powered over Ethernet (PoE) for a clean installation.'::text, '{"Power":"PoE","Coverage":"Wide-area"}'::jsonb, false, false, false),
  ('solar-equipment'::text, 'Monocrystalline Solar Panel'::text, 'monocrystalline-solar-panel'::text, null::text, 'High-efficiency solar panels for homes, farms and businesses.'::text, 'Monocrystalline cells for strong output even in low light. Aluminium frame and tempered glass built for Kenyan weather. Choose the wattage that matches your system design.'::text, '{"Cell type":"Monocrystalline","Frame":"Anodised aluminium","Performance warranty":"25 years","Product warranty":"10 years"}'::jsonb, true, true, false),
  ('solar-equipment'::text, 'Solar Charge Controller'::text, 'solar-charge-controller'::text, null::text, 'Protects your battery and improves charging efficiency.'::text, 'LCD charge controller with overload, short-circuit and over-charge protection. MPPT models harvest more power from your panels.'::text, '{"Display":"LCD","Protection":"Overload, short circuit, over-charge"}'::jsonb, false, false, false),
  ('solar-equipment'::text, 'Solar Cable & MC4 Connector Kit'::text, 'solar-cable-mc4-kit'::text, null::text, 'UV-resistant solar cable with MC4 connectors.'::text, 'Twin-core solar cable with a pair of MC4 connectors fitted. Sunlight and weather resistant.'::text, '{"Cable":"4mm2 solar cable","Connectors":"MC4 pair"}'::jsonb, false, false, false),
  ('inverters-batteries'::text, 'Deep Cycle Solar Battery'::text, 'deep-cycle-solar-battery'::text, null::text, '12V deep-cycle batteries for solar, inverter and UPS systems.'::text, 'Maintenance-free deep cycle battery made for daily charge and discharge. Pair with a solar charge controller and inverter.'::text, '{"Voltage":"12V","Type":"Deep cycle, maintenance free","Warranty":"1 year"}'::jsonb, true, true, false),
  ('inverters-batteries'::text, 'Hybrid Solar Inverter'::text, 'hybrid-solar-inverter'::text, null::text, 'Pure sine wave hybrid inverter with built-in solar charger.'::text, 'Runs household appliances from batteries and solar, and switches to grid power when needed. Pure sine wave output with an LCD status display.'::text, '{"Output":"Pure sine wave","Display":"LCD","Input":"Solar + grid","Warranty":"2 years"}'::jsonb, true, false, true),
  ('water-pumps'::text, 'Surface Water Pump'::text, 'surface-water-pump'::text, null::text, 'Electric surface pumps for tanks, gardens and small farms.'::text, 'Copper-wound motor with a cast-iron pump head for steady water delivery. Ideal for filling tanks and irrigation.'::text, '{"Motor":"Copper winding","Pump head":"Cast iron","Power":"Single phase 240V"}'::jsonb, false, true, false),
  ('water-pumps'::text, 'Pressure Booster Pump'::text, 'pressure-booster-pump'::text, null::text, 'Automatic booster pump with pressure vessel and gauge.'::text, 'Boost low water pressure throughout the house. Automatic start and stop with pressure switch and gauge.'::text, '{"Control":"Automatic pressure switch","Gauge":"Included","Power":"Single phase 240V"}'::jsonb, false, false, true),
  ('water-pumps'::text, 'Borehole Submersible Pump'::text, 'borehole-submersible-pump'::text, null::text, 'Stainless-steel submersible pumps for boreholes and wells.'::text, 'Stainless-steel body for long life underwater. Supplied with a cable. Choose the power for your depth and flow requirements.'::text, '{"Body":"Stainless steel","Use":"Boreholes and deep wells"}'::jsonb, false, false, false),
  ('power-equipment'::text, 'Petrol Generator'::text, 'petrol-generator'::text, null::text, 'Portable petrol generators with recoil start.'::text, 'Reliable backup power for homes, shops and sites. Air-cooled engine, AVR for stable output and wheels for easy moving.'::text, '{"Fuel":"Petrol","Start":"Recoil (key start on larger sizes)","Output":"230V AC"}'::jsonb, false, true, false),
  ('power-equipment'::text, 'Automatic Voltage Regulator'::text, 'automatic-voltage-regulator'::text, null::text, 'Protect TVs, fridges and computers from voltage spikes.'::text, 'Stabilises mains voltage and protects your appliances. Digital voltage display and time-delay protection.'::text, '{"Display":"Digital voltage","Protection":"Over and under voltage"}'::jsonb, false, false, false),
  ('electronics'::text, 'Power Bank'::text, 'power-bank'::text, null::text, 'Fast-charging power banks with dual USB output.'::text, 'Keep phones, earbuds and tablets charged on the go. LED charge indicator and dual USB output.'::text, '{"Output":"Dual USB","Indicator":"LED"}'::jsonb, false, false, false),
  ('electronics'::text, 'Wireless Earbuds'::text, 'wireless-earbuds'::text, null::text, 'Bluetooth earbuds with charging case.'::text, 'True wireless earbuds with clear sound, touch controls and a pocket charging case.'::text, '{"Connectivity":"Bluetooth 5.3","Case battery":"Up to 20 hours total"}'::jsonb, false, false, true),
  ('other-accessories'::text, 'Surge-Protected Extension Socket'::text, 'surge-protected-extension-socket'::text, null::text, 'Extension sockets with surge protection and switch.'::text, 'Safe multi-way extension with surge protection, individual overload protection and a 3-metre cable.'::text, '{"Cable":"3 metres","Protection":"Surge and overload"}'::jsonb, false, false, false),
  ('other-accessories'::text, 'TV Wall Mount Bracket'::text, 'tv-wall-mount-bracket'::text, null::text, 'Tilting TV wall brackets for flat-screen TVs.'::text, 'Strong steel bracket with tilt adjustment. Screws and fixings included.'::text, '{"Material":"Steel","Includes":"Screws and fixings"}'::jsonb, false, false, false)
) as v(category_slug, name, slug, brand, short_description, description, specs, is_featured, is_popular, is_new)
join public.categories c on c.slug = v.category_slug
on conflict (slug) do nothing;

insert into public.product_images (product_id, url, alt, sort_order)
select p.id, v.url, v.alt, v.sort_order
from (values
  ('water-tank'::text, '/sample-products/water-tank-1.svg'::text, 'Water Tank'::text, 0::int),
  ('triple-layer-water-tank'::text, '/sample-products/triple-layer-water-tank-1.svg'::text, 'Triple-Layer Water Tank'::text, 0::int),
  ('tank-fittings-kit'::text, '/sample-products/tank-fittings-kit-1.svg'::text, 'Tank Fittings Kit'::text, 0::int),
  ('samsung-4k-uhd-smart-tv'::text, '/sample-products/samsung-4k-uhd-smart-tv-1.svg'::text, 'Samsung 4K UHD Smart TV'::text, 0::int),
  ('lg-uhd-smart-tv'::text, '/sample-products/lg-uhd-smart-tv-1.svg'::text, 'LG UHD Smart TV'::text, 0::int),
  ('hisense-full-hd-smart-tv'::text, '/sample-products/hisense-full-hd-smart-tv-1.svg'::text, 'Hisense Full HD Smart TV'::text, 0::int),
  ('portable-bluetooth-speaker'::text, '/sample-products/portable-bluetooth-speaker-1.svg'::text, 'Portable Bluetooth Speaker'::text, 0::int),
  ('soundbar-with-subwoofer'::text, '/sample-products/soundbar-with-subwoofer-1.svg'::text, 'Soundbar with Subwoofer'::text, 0::int),
  ('home-theatre-system'::text, '/sample-products/home-theatre-system-1.svg'::text, 'Home Theatre System'::text, 0::int),
  ('single-door-refrigerator'::text, '/sample-products/single-door-refrigerator-1.svg'::text, 'Single Door Refrigerator'::text, 0::int),
  ('double-door-refrigerator'::text, '/sample-products/double-door-refrigerator-1.svg'::text, 'Double Door Refrigerator'::text, 0::int),
  ('side-by-side-refrigerator'::text, '/sample-products/side-by-side-refrigerator-1.svg'::text, 'Side-by-Side Refrigerator'::text, 0::int),
  ('chest-freezer'::text, '/sample-products/chest-freezer-1.svg'::text, 'Chest Freezer'::text, 0::int),
  ('microwave-oven'::text, '/sample-products/microwave-oven-1.svg'::text, 'Microwave Oven'::text, 0::int),
  ('front-load-washing-machine'::text, '/sample-products/front-load-washing-machine-1.svg'::text, 'Front-Load Washing Machine'::text, 0::int),
  ('business-laptop-15'::text, '/sample-products/business-laptop-15-1.svg'::text, 'Business Laptop 15.6 Inch'::text, 0::int),
  ('desktop-computer-set'::text, '/sample-products/desktop-computer-set-1.svg'::text, 'Desktop Computer Set'::text, 0::int),
  ('led-monitor'::text, '/sample-products/led-monitor-1.svg'::text, 'LED Monitor'::text, 0::int),
  ('outdoor-cctv-bullet-camera'::text, '/sample-products/outdoor-cctv-bullet-camera-1.svg'::text, 'Outdoor CCTV Bullet Camera'::text, 0::int),
  ('cctv-camera-kit'::text, '/sample-products/cctv-camera-kit-1.svg'::text, 'CCTV Camera Kit'::text, 0::int),
  ('dvr-nvr-recorder'::text, '/sample-products/dvr-nvr-recorder-1.svg'::text, 'DVR / NVR Recorder'::text, 0::int),
  ('wifi-router'::text, '/sample-products/wifi-router-1.svg'::text, 'Wi-Fi Router'::text, 0::int),
  ('network-switch'::text, '/sample-products/network-switch-1.svg'::text, 'Gigabit Network Switch'::text, 0::int),
  ('wireless-access-point'::text, '/sample-products/wireless-access-point-1.svg'::text, 'Wireless Access Point'::text, 0::int),
  ('monocrystalline-solar-panel'::text, '/sample-products/monocrystalline-solar-panel-1.svg'::text, 'Monocrystalline Solar Panel'::text, 0::int),
  ('solar-charge-controller'::text, '/sample-products/solar-charge-controller-1.svg'::text, 'Solar Charge Controller'::text, 0::int),
  ('solar-cable-mc4-kit'::text, '/sample-products/solar-cable-mc4-kit-1.svg'::text, 'Solar Cable & MC4 Connector Kit'::text, 0::int),
  ('deep-cycle-solar-battery'::text, '/sample-products/deep-cycle-solar-battery-1.svg'::text, 'Deep Cycle Solar Battery'::text, 0::int),
  ('hybrid-solar-inverter'::text, '/sample-products/hybrid-solar-inverter-1.svg'::text, 'Hybrid Solar Inverter'::text, 0::int),
  ('surface-water-pump'::text, '/sample-products/surface-water-pump-1.svg'::text, 'Surface Water Pump'::text, 0::int),
  ('pressure-booster-pump'::text, '/sample-products/pressure-booster-pump-1.svg'::text, 'Pressure Booster Pump'::text, 0::int),
  ('borehole-submersible-pump'::text, '/sample-products/borehole-submersible-pump-1.svg'::text, 'Borehole Submersible Pump'::text, 0::int),
  ('petrol-generator'::text, '/sample-products/petrol-generator-1.svg'::text, 'Petrol Generator'::text, 0::int),
  ('automatic-voltage-regulator'::text, '/sample-products/automatic-voltage-regulator-1.svg'::text, 'Automatic Voltage Regulator'::text, 0::int),
  ('power-bank'::text, '/sample-products/power-bank-1.svg'::text, 'Power Bank'::text, 0::int),
  ('wireless-earbuds'::text, '/sample-products/wireless-earbuds-1.svg'::text, 'Wireless Earbuds'::text, 0::int),
  ('surge-protected-extension-socket'::text, '/sample-products/surge-protected-extension-socket-1.svg'::text, 'Surge-Protected Extension Socket'::text, 0::int),
  ('tv-wall-mount-bracket'::text, '/sample-products/tv-wall-mount-bracket-1.svg'::text, 'TV Wall Mount Bracket'::text, 0::int)
) as v(product_slug, url, alt, sort_order)
join public.products p on p.slug = v.product_slug
where not exists (
  select 1 from public.product_images pi where pi.product_id = p.id and pi.url = v.url
);

insert into public.product_images (product_id, url, alt, sort_order)
select p.id, v.url, v.alt, v.sort_order
from (values
  ('water-tank'::text, '/sample-products/water-tank-2.svg'::text, 'Water Tank - detail view'::text, 1::int),
  ('triple-layer-water-tank'::text, '/sample-products/triple-layer-water-tank-2.svg'::text, 'Triple-Layer Water Tank - detail view'::text, 1::int),
  ('tank-fittings-kit'::text, '/sample-products/tank-fittings-kit-2.svg'::text, 'Tank Fittings Kit - detail view'::text, 1::int),
  ('samsung-4k-uhd-smart-tv'::text, '/sample-products/samsung-4k-uhd-smart-tv-2.svg'::text, 'Samsung 4K UHD Smart TV - detail view'::text, 1::int),
  ('lg-uhd-smart-tv'::text, '/sample-products/lg-uhd-smart-tv-2.svg'::text, 'LG UHD Smart TV - detail view'::text, 1::int),
  ('hisense-full-hd-smart-tv'::text, '/sample-products/hisense-full-hd-smart-tv-2.svg'::text, 'Hisense Full HD Smart TV - detail view'::text, 1::int),
  ('portable-bluetooth-speaker'::text, '/sample-products/portable-bluetooth-speaker-2.svg'::text, 'Portable Bluetooth Speaker - detail view'::text, 1::int),
  ('soundbar-with-subwoofer'::text, '/sample-products/soundbar-with-subwoofer-2.svg'::text, 'Soundbar with Subwoofer - detail view'::text, 1::int),
  ('home-theatre-system'::text, '/sample-products/home-theatre-system-2.svg'::text, 'Home Theatre System - detail view'::text, 1::int),
  ('single-door-refrigerator'::text, '/sample-products/single-door-refrigerator-2.svg'::text, 'Single Door Refrigerator - detail view'::text, 1::int),
  ('double-door-refrigerator'::text, '/sample-products/double-door-refrigerator-2.svg'::text, 'Double Door Refrigerator - detail view'::text, 1::int),
  ('side-by-side-refrigerator'::text, '/sample-products/side-by-side-refrigerator-2.svg'::text, 'Side-by-Side Refrigerator - detail view'::text, 1::int),
  ('chest-freezer'::text, '/sample-products/chest-freezer-2.svg'::text, 'Chest Freezer - detail view'::text, 1::int),
  ('microwave-oven'::text, '/sample-products/microwave-oven-2.svg'::text, 'Microwave Oven - detail view'::text, 1::int),
  ('front-load-washing-machine'::text, '/sample-products/front-load-washing-machine-2.svg'::text, 'Front-Load Washing Machine - detail view'::text, 1::int),
  ('business-laptop-15'::text, '/sample-products/business-laptop-15-2.svg'::text, 'Business Laptop 15.6 Inch - detail view'::text, 1::int),
  ('desktop-computer-set'::text, '/sample-products/desktop-computer-set-2.svg'::text, 'Desktop Computer Set - detail view'::text, 1::int),
  ('led-monitor'::text, '/sample-products/led-monitor-2.svg'::text, 'LED Monitor - detail view'::text, 1::int),
  ('outdoor-cctv-bullet-camera'::text, '/sample-products/outdoor-cctv-bullet-camera-2.svg'::text, 'Outdoor CCTV Bullet Camera - detail view'::text, 1::int),
  ('cctv-camera-kit'::text, '/sample-products/cctv-camera-kit-2.svg'::text, 'CCTV Camera Kit - detail view'::text, 1::int),
  ('dvr-nvr-recorder'::text, '/sample-products/dvr-nvr-recorder-2.svg'::text, 'DVR / NVR Recorder - detail view'::text, 1::int),
  ('wifi-router'::text, '/sample-products/wifi-router-2.svg'::text, 'Wi-Fi Router - detail view'::text, 1::int),
  ('network-switch'::text, '/sample-products/network-switch-2.svg'::text, 'Gigabit Network Switch - detail view'::text, 1::int),
  ('wireless-access-point'::text, '/sample-products/wireless-access-point-2.svg'::text, 'Wireless Access Point - detail view'::text, 1::int),
  ('monocrystalline-solar-panel'::text, '/sample-products/monocrystalline-solar-panel-2.svg'::text, 'Monocrystalline Solar Panel - detail view'::text, 1::int),
  ('solar-charge-controller'::text, '/sample-products/solar-charge-controller-2.svg'::text, 'Solar Charge Controller - detail view'::text, 1::int),
  ('solar-cable-mc4-kit'::text, '/sample-products/solar-cable-mc4-kit-2.svg'::text, 'Solar Cable & MC4 Connector Kit - detail view'::text, 1::int),
  ('deep-cycle-solar-battery'::text, '/sample-products/deep-cycle-solar-battery-2.svg'::text, 'Deep Cycle Solar Battery - detail view'::text, 1::int),
  ('hybrid-solar-inverter'::text, '/sample-products/hybrid-solar-inverter-2.svg'::text, 'Hybrid Solar Inverter - detail view'::text, 1::int),
  ('surface-water-pump'::text, '/sample-products/surface-water-pump-2.svg'::text, 'Surface Water Pump - detail view'::text, 1::int),
  ('pressure-booster-pump'::text, '/sample-products/pressure-booster-pump-2.svg'::text, 'Pressure Booster Pump - detail view'::text, 1::int),
  ('borehole-submersible-pump'::text, '/sample-products/borehole-submersible-pump-2.svg'::text, 'Borehole Submersible Pump - detail view'::text, 1::int),
  ('petrol-generator'::text, '/sample-products/petrol-generator-2.svg'::text, 'Petrol Generator - detail view'::text, 1::int),
  ('automatic-voltage-regulator'::text, '/sample-products/automatic-voltage-regulator-2.svg'::text, 'Automatic Voltage Regulator - detail view'::text, 1::int),
  ('power-bank'::text, '/sample-products/power-bank-2.svg'::text, 'Power Bank - detail view'::text, 1::int),
  ('wireless-earbuds'::text, '/sample-products/wireless-earbuds-2.svg'::text, 'Wireless Earbuds - detail view'::text, 1::int),
  ('surge-protected-extension-socket'::text, '/sample-products/surge-protected-extension-socket-2.svg'::text, 'Surge-Protected Extension Socket - detail view'::text, 1::int),
  ('tv-wall-mount-bracket'::text, '/sample-products/tv-wall-mount-bracket-2.svg'::text, 'TV Wall Mount Bracket - detail view'::text, 1::int)
) as v(product_slug, url, alt, sort_order)
join public.products p on p.slug = v.product_slug
where not exists (
  select 1 from public.product_images pi where pi.product_id = p.id and pi.url = v.url
);

insert into public.product_variants (product_id, label, sku, price, previous_price, stock, availability, specs, sort_order)
select p.id, v.label, v.sku, v.price, v.previous_price, v.stock, v.availability, v.specs, v.sort_order
from (values
  ('water-tank'::text, '100 Litres'::text, 'TNK-100LITRES'::text, 2800::numeric, null::numeric, 20::int, 'in_stock'::text, '{"Capacity":"100 Litres"}'::jsonb, 0::int),
  ('water-tank'::text, '200 Litres'::text, 'TNK-200LITRES'::text, 4200::numeric, null::numeric, 18::int, 'in_stock'::text, '{"Capacity":"200 Litres"}'::jsonb, 1::int),
  ('water-tank'::text, '300 Litres'::text, 'TNK-300LITRES'::text, 5600::numeric, null::numeric, 14::int, 'in_stock'::text, '{"Capacity":"300 Litres"}'::jsonb, 2::int),
  ('water-tank'::text, '500 Litres'::text, 'TNK-500LITRES'::text, 8500::numeric, 9800::numeric, 25::int, 'in_stock'::text, '{"Capacity":"500 Litres"}'::jsonb, 3::int),
  ('water-tank'::text, '1,000 Litres'::text, 'TNK-1000LITRES'::text, 15500::numeric, 17500::numeric, 22::int, 'in_stock'::text, '{"Capacity":"1,000 Litres"}'::jsonb, 4::int),
  ('water-tank'::text, '1,500 Litres'::text, 'TNK-1500LITRES'::text, 21500::numeric, null::numeric, 10::int, 'in_stock'::text, '{"Capacity":"1,500 Litres"}'::jsonb, 5::int),
  ('water-tank'::text, '2,000 Litres'::text, 'TNK-2000LITRES'::text, 28000::numeric, 32000::numeric, 15::int, 'in_stock'::text, '{"Capacity":"2,000 Litres"}'::jsonb, 6::int),
  ('water-tank'::text, '2,500 Litres'::text, 'TNK-2500LITRES'::text, 34500::numeric, null::numeric, 9::int, 'in_stock'::text, '{"Capacity":"2,500 Litres"}'::jsonb, 7::int),
  ('water-tank'::text, '3,000 Litres'::text, 'TNK-3000LITRES'::text, 41000::numeric, null::numeric, 12::int, 'in_stock'::text, '{"Capacity":"3,000 Litres"}'::jsonb, 8::int),
  ('water-tank'::text, '4,000 Litres'::text, 'TNK-4000LITRES'::text, 54000::numeric, null::numeric, 6::int, 'in_stock'::text, '{"Capacity":"4,000 Litres"}'::jsonb, 9::int),
  ('water-tank'::text, '5,000 Litres'::text, 'TNK-5000LITRES'::text, 66000::numeric, 72000::numeric, 8::int, 'in_stock'::text, '{"Capacity":"5,000 Litres"}'::jsonb, 10::int),
  ('water-tank'::text, '6,000 Litres'::text, 'TNK-6000LITRES'::text, 79000::numeric, null::numeric, 4::int, 'in_stock'::text, '{"Capacity":"6,000 Litres"}'::jsonb, 11::int),
  ('water-tank'::text, '8,000 Litres'::text, 'TNK-8000LITRES'::text, 104000::numeric, null::numeric, 3::int, 'in_stock'::text, '{"Capacity":"8,000 Litres"}'::jsonb, 12::int),
  ('water-tank'::text, '10,000 Litres'::text, 'TNK-10000LITRES'::text, 128000::numeric, null::numeric, 5::int, 'in_stock'::text, '{"Capacity":"10,000 Litres"}'::jsonb, 13::int),
  ('water-tank'::text, '12,000 Litres'::text, 'TNK-12000LITRES'::text, 152000::numeric, null::numeric, 2::int, 'in_stock'::text, '{"Capacity":"12,000 Litres"}'::jsonb, 14::int),
  ('water-tank'::text, '15,000 Litres'::text, 'TNK-15000LITRES'::text, 187000::numeric, null::numeric, 2::int, 'in_stock'::text, '{"Capacity":"15,000 Litres"}'::jsonb, 15::int),
  ('water-tank'::text, '20,000 Litres'::text, 'TNK-20000LITRES'::text, 245000::numeric, null::numeric, 0::int, 'on_order'::text, '{"Capacity":"20,000 Litres"}'::jsonb, 16::int),
  ('water-tank'::text, '24,000 Litres'::text, 'TNK-24000LITRES'::text, 290000::numeric, null::numeric, 0::int, 'on_order'::text, '{"Capacity":"24,000 Litres"}'::jsonb, 17::int),
  ('triple-layer-water-tank'::text, '500 Litres'::text, 'TNK-3L-500LITRES'::text, 10500::numeric, null::numeric, 12::int, 'in_stock'::text, '{"Capacity":"500 Litres"}'::jsonb, 0::int),
  ('triple-layer-water-tank'::text, '1,000 Litres'::text, 'TNK-3L-1000LITRES'::text, 18500::numeric, 20500::numeric, 10::int, 'in_stock'::text, '{"Capacity":"1,000 Litres"}'::jsonb, 1::int),
  ('triple-layer-water-tank'::text, '2,000 Litres'::text, 'TNK-3L-2000LITRES'::text, 33500::numeric, null::numeric, 8::int, 'in_stock'::text, '{"Capacity":"2,000 Litres"}'::jsonb, 2::int),
  ('triple-layer-water-tank'::text, '3,000 Litres'::text, 'TNK-3L-3000LITRES'::text, 48500::numeric, null::numeric, 5::int, 'in_stock'::text, '{"Capacity":"3,000 Litres"}'::jsonb, 3::int),
  ('triple-layer-water-tank'::text, '5,000 Litres'::text, 'TNK-3L-5000LITRES'::text, 76500::numeric, null::numeric, 4::int, 'in_stock'::text, '{"Capacity":"5,000 Litres"}'::jsonb, 4::int),
  ('triple-layer-water-tank'::text, '10,000 Litres'::text, 'TNK-3L-10000LITRES'::text, 146000::numeric, null::numeric, 2::int, 'in_stock'::text, '{"Capacity":"10,000 Litres"}'::jsonb, 5::int),
  ('tank-fittings-kit'::text, '1/2 inch'::text, 'TNK-FIT-12INCH'::text, 1800::numeric, null::numeric, 30::int, 'in_stock'::text, '{"Pipe size":"1/2 inch"}'::jsonb, 0::int),
  ('tank-fittings-kit'::text, '3/4 inch'::text, 'TNK-FIT-34INCH'::text, 2600::numeric, null::numeric, 24::int, 'in_stock'::text, '{"Pipe size":"3/4 inch"}'::jsonb, 1::int),
  ('tank-fittings-kit'::text, '1 inch'::text, 'TNK-FIT-1INCH'::text, 3800::numeric, null::numeric, 15::int, 'in_stock'::text, '{"Pipe size":"1 inch"}'::jsonb, 2::int),
  ('samsung-4k-uhd-smart-tv'::text, '43 Inch'::text, 'TV-SAM-43INCH'::text, 46500::numeric, 52000::numeric, 10::int, 'in_stock'::text, '{"Screen size":"43 Inch"}'::jsonb, 0::int),
  ('samsung-4k-uhd-smart-tv'::text, '50 Inch'::text, 'TV-SAM-50INCH'::text, 62000::numeric, null::numeric, 8::int, 'in_stock'::text, '{"Screen size":"50 Inch"}'::jsonb, 1::int),
  ('samsung-4k-uhd-smart-tv'::text, '55 Inch'::text, 'TV-SAM-55INCH'::text, 74500::numeric, 82000::numeric, 7::int, 'in_stock'::text, '{"Screen size":"55 Inch"}'::jsonb, 2::int),
  ('samsung-4k-uhd-smart-tv'::text, '65 Inch'::text, 'TV-SAM-65INCH'::text, 109000::numeric, null::numeric, 3::int, 'in_stock'::text, '{"Screen size":"65 Inch"}'::jsonb, 3::int),
  ('lg-uhd-smart-tv'::text, '50 Inch'::text, 'TV-LG-50INCH'::text, 63500::numeric, null::numeric, 6::int, 'in_stock'::text, '{"Screen size":"50 Inch"}'::jsonb, 0::int),
  ('lg-uhd-smart-tv'::text, '55 Inch'::text, 'TV-LG-55INCH'::text, 77000::numeric, null::numeric, 5::int, 'in_stock'::text, '{"Screen size":"55 Inch"}'::jsonb, 1::int),
  ('lg-uhd-smart-tv'::text, '65 Inch'::text, 'TV-LG-65INCH'::text, 112000::numeric, 119000::numeric, 2::int, 'in_stock'::text, '{"Screen size":"65 Inch"}'::jsonb, 2::int),
  ('hisense-full-hd-smart-tv'::text, '32 Inch'::text, 'TV-HIS-32INCH'::text, 19500::numeric, 22500::numeric, 14::int, 'in_stock'::text, '{"Screen size":"32 Inch"}'::jsonb, 0::int),
  ('hisense-full-hd-smart-tv'::text, '43 Inch'::text, 'TV-HIS-43INCH'::text, 38500::numeric, null::numeric, 9::int, 'in_stock'::text, '{"Screen size":"43 Inch"}'::jsonb, 1::int),
  ('portable-bluetooth-speaker'::text, 'Compact 20W'::text, 'SPK-BT-COMPACT20W'::text, 5800::numeric, 6900::numeric, 16::int, 'in_stock'::text, '{"Power":"Compact 20W"}'::jsonb, 0::int),
  ('portable-bluetooth-speaker'::text, 'Medium 40W'::text, 'SPK-BT-MEDIUM40W'::text, 9500::numeric, null::numeric, 12::int, 'in_stock'::text, '{"Power":"Medium 40W"}'::jsonb, 1::int),
  ('portable-bluetooth-speaker'::text, 'Party 100W'::text, 'SPK-BT-PARTY100W'::text, 24500::numeric, null::numeric, 4::int, 'in_stock'::text, '{"Power":"Party 100W"}'::jsonb, 2::int),
  ('soundbar-with-subwoofer'::text, '2.1 Channel 120W'::text, 'SPK-SB-21CHANNEL120W'::text, 14900::numeric, 17500::numeric, 9::int, 'in_stock'::text, '{"Configuration":"2.1 Channel 120W"}'::jsonb, 0::int),
  ('soundbar-with-subwoofer'::text, '2.1 Channel 300W'::text, 'SPK-SB-21CHANNEL300W'::text, 26500::numeric, null::numeric, 6::int, 'in_stock'::text, '{"Configuration":"2.1 Channel 300W"}'::jsonb, 1::int),
  ('soundbar-with-subwoofer'::text, '5.1 Channel 500W'::text, 'SPK-SB-51CHANNEL500W'::text, 42000::numeric, null::numeric, 3::int, 'in_stock'::text, '{"Configuration":"5.1 Channel 500W"}'::jsonb, 2::int),
  ('home-theatre-system'::text, '5.1 Channel'::text, 'SPK-HT-51CHANNEL'::text, 29500::numeric, null::numeric, 5::int, 'in_stock'::text, '{"Channels":"5.1 Channel"}'::jsonb, 0::int),
  ('home-theatre-system'::text, '7.1 Channel'::text, 'SPK-HT-71CHANNEL'::text, 54000::numeric, 59000::numeric, 2::int, 'in_stock'::text, '{"Channels":"7.1 Channel"}'::jsonb, 1::int),
  ('single-door-refrigerator'::text, '100 Litres'::text, 'FRG-1D-100LITRES'::text, 21500::numeric, null::numeric, 10::int, 'in_stock'::text, '{"Capacity":"100 Litres"}'::jsonb, 0::int),
  ('single-door-refrigerator'::text, '150 Litres'::text, 'FRG-1D-150LITRES'::text, 27500::numeric, 29900::numeric, 8::int, 'in_stock'::text, '{"Capacity":"150 Litres"}'::jsonb, 1::int),
  ('single-door-refrigerator'::text, '200 Litres'::text, 'FRG-1D-200LITRES'::text, 33000::numeric, null::numeric, 6::int, 'in_stock'::text, '{"Capacity":"200 Litres"}'::jsonb, 2::int),
  ('double-door-refrigerator'::text, '250 Litres'::text, 'FRG-2D-250LITRES'::text, 52000::numeric, null::numeric, 7::int, 'in_stock'::text, '{"Capacity":"250 Litres"}'::jsonb, 0::int),
  ('double-door-refrigerator'::text, '300 Litres'::text, 'FRG-2D-300LITRES'::text, 61500::numeric, 67000::numeric, 6::int, 'in_stock'::text, '{"Capacity":"300 Litres"}'::jsonb, 1::int),
  ('double-door-refrigerator'::text, '350 Litres'::text, 'FRG-2D-350LITRES'::text, 72000::numeric, null::numeric, 4::int, 'in_stock'::text, '{"Capacity":"350 Litres"}'::jsonb, 2::int),
  ('side-by-side-refrigerator'::text, '500 Litres'::text, 'FRG-SBS-500LITRES'::text, 129000::numeric, null::numeric, 3::int, 'in_stock'::text, '{"Capacity":"500 Litres"}'::jsonb, 0::int),
  ('side-by-side-refrigerator'::text, '600 Litres'::text, 'FRG-SBS-600LITRES'::text, 159000::numeric, 175000::numeric, 2::int, 'in_stock'::text, '{"Capacity":"600 Litres"}'::jsonb, 1::int),
  ('chest-freezer'::text, '200 Litres'::text, 'FRZ-CH-200LITRES'::text, 36500::numeric, null::numeric, 8::int, 'in_stock'::text, '{"Capacity":"200 Litres"}'::jsonb, 0::int),
  ('chest-freezer'::text, '300 Litres'::text, 'FRZ-CH-300LITRES'::text, 46000::numeric, 49500::numeric, 6::int, 'in_stock'::text, '{"Capacity":"300 Litres"}'::jsonb, 1::int),
  ('chest-freezer'::text, '400 Litres'::text, 'FRZ-CH-400LITRES'::text, 58500::numeric, null::numeric, 4::int, 'in_stock'::text, '{"Capacity":"400 Litres"}'::jsonb, 2::int),
  ('chest-freezer'::text, '500 Litres'::text, 'FRZ-CH-500LITRES'::text, 69900::numeric, null::numeric, 3::int, 'in_stock'::text, '{"Capacity":"500 Litres"}'::jsonb, 3::int),
  ('microwave-oven'::text, '20 Litres'::text, 'APP-MW-20LITRES'::text, 9500::numeric, 10900::numeric, 12::int, 'in_stock'::text, '{"Capacity":"20 Litres"}'::jsonb, 0::int),
  ('microwave-oven'::text, '25 Litres'::text, 'APP-MW-25LITRES'::text, 12500::numeric, null::numeric, 9::int, 'in_stock'::text, '{"Capacity":"25 Litres"}'::jsonb, 1::int),
  ('microwave-oven'::text, '30 Litres'::text, 'APP-MW-30LITRES'::text, 16800::numeric, null::numeric, 5::int, 'in_stock'::text, '{"Capacity":"30 Litres"}'::jsonb, 2::int),
  ('front-load-washing-machine'::text, '7 kg'::text, 'APP-WM-7KG'::text, 49000::numeric, null::numeric, 5::int, 'in_stock'::text, '{"Capacity":"7 kg"}'::jsonb, 0::int),
  ('front-load-washing-machine'::text, '9 kg'::text, 'APP-WM-9KG'::text, 62500::numeric, 67000::numeric, 4::int, 'in_stock'::text, '{"Capacity":"9 kg"}'::jsonb, 1::int),
  ('front-load-washing-machine'::text, '10.5 kg'::text, 'APP-WM-105KG'::text, 78000::numeric, null::numeric, 2::int, 'in_stock'::text, '{"Capacity":"10.5 kg"}'::jsonb, 2::int),
  ('business-laptop-15'::text, 'Core i3 / 8GB / 256GB SSD'::text, 'PC-LAP-COREI38GB256GB'::text, 52000::numeric, null::numeric, 8::int, 'in_stock'::text, '{"Configuration":"Core i3 / 8GB / 256GB SSD"}'::jsonb, 0::int),
  ('business-laptop-15'::text, 'Core i5 / 8GB / 512GB SSD'::text, 'PC-LAP-COREI58GB512GB'::text, 68500::numeric, 74000::numeric, 6::int, 'in_stock'::text, '{"Configuration":"Core i5 / 8GB / 512GB SSD"}'::jsonb, 1::int),
  ('business-laptop-15'::text, 'Core i7 / 16GB / 512GB SSD'::text, 'PC-LAP-COREI716GB512G'::text, 94000::numeric, null::numeric, 3::int, 'in_stock'::text, '{"Configuration":"Core i7 / 16GB / 512GB SSD"}'::jsonb, 2::int),
  ('desktop-computer-set'::text, 'Core i3 / 4GB / 500GB HDD'::text, 'PC-DT-COREI34GB500GB'::text, 36500::numeric, null::numeric, 6::int, 'in_stock'::text, '{"Configuration":"Core i3 / 4GB / 500GB HDD"}'::jsonb, 0::int),
  ('desktop-computer-set'::text, 'Core i5 / 8GB / 256GB SSD'::text, 'PC-DT-COREI58GB256GB'::text, 52000::numeric, null::numeric, 4::int, 'in_stock'::text, '{"Configuration":"Core i5 / 8GB / 256GB SSD"}'::jsonb, 1::int),
  ('led-monitor'::text, '22 Inch Full HD'::text, 'PC-MON-22INCHFULLHD'::text, 13500::numeric, null::numeric, 12::int, 'in_stock'::text, '{"Screen size":"22 Inch Full HD"}'::jsonb, 0::int),
  ('led-monitor'::text, '24 Inch Full HD'::text, 'PC-MON-24INCHFULLHD'::text, 16500::numeric, 18500::numeric, 10::int, 'in_stock'::text, '{"Screen size":"24 Inch Full HD"}'::jsonb, 1::int),
  ('led-monitor'::text, '27 Inch QHD'::text, 'PC-MON-27INCHQHD'::text, 28500::numeric, null::numeric, 4::int, 'in_stock'::text, '{"Screen size":"27 Inch QHD"}'::jsonb, 2::int),
  ('outdoor-cctv-bullet-camera'::text, '2MP (1080p)'::text, 'CCTV-CAM-2MP1080P'::text, 3800::numeric, null::numeric, 25::int, 'in_stock'::text, '{"Resolution":"2MP (1080p)"}'::jsonb, 0::int),
  ('outdoor-cctv-bullet-camera'::text, '5MP'::text, 'CCTV-CAM-5MP'::text, 6200::numeric, 6900::numeric, 14::int, 'in_stock'::text, '{"Resolution":"5MP"}'::jsonb, 1::int),
  ('cctv-camera-kit'::text, '4 Camera Kit'::text, 'CCTV-KIT-4CAMERAKIT'::text, 34500::numeric, 39000::numeric, 7::int, 'in_stock'::text, '{"Kit size":"4 Camera Kit"}'::jsonb, 0::int),
  ('cctv-camera-kit'::text, '8 Camera Kit'::text, 'CCTV-KIT-8CAMERAKIT'::text, 62000::numeric, null::numeric, 4::int, 'in_stock'::text, '{"Kit size":"8 Camera Kit"}'::jsonb, 1::int),
  ('dvr-nvr-recorder'::text, '4 Channel DVR'::text, 'CCTV-REC-4CHANNELDVR'::text, 6500::numeric, null::numeric, 10::int, 'in_stock'::text, '{"Channels":"4 Channel DVR"}'::jsonb, 0::int),
  ('dvr-nvr-recorder'::text, '8 Channel DVR'::text, 'CCTV-REC-8CHANNELDVR'::text, 9800::numeric, null::numeric, 8::int, 'in_stock'::text, '{"Channels":"8 Channel DVR"}'::jsonb, 1::int),
  ('dvr-nvr-recorder'::text, '16 Channel NVR'::text, 'CCTV-REC-16CHANNELNVR'::text, 21500::numeric, null::numeric, 3::int, 'in_stock'::text, '{"Channels":"16 Channel NVR"}'::jsonb, 2::int),
  ('wifi-router'::text, 'AC1200 Dual Band'::text, 'NET-RTR-AC1200DUALBAND'::text, 3900::numeric, null::numeric, 20::int, 'in_stock'::text, '{"Model":"AC1200 Dual Band"}'::jsonb, 0::int),
  ('wifi-router'::text, 'AX1800 Wi-Fi 6'::text, 'NET-RTR-AX1800WIFI6'::text, 8900::numeric, 9900::numeric, 10::int, 'in_stock'::text, '{"Model":"AX1800 Wi-Fi 6"}'::jsonb, 1::int),
  ('wifi-router'::text, '4G LTE (SIM) Router'::text, 'NET-RTR-4GLTESIMROUTER'::text, 7500::numeric, null::numeric, 8::int, 'in_stock'::text, '{"Model":"4G LTE (SIM) Router"}'::jsonb, 2::int),
  ('network-switch'::text, '8-Port'::text, 'NET-SW-8PORT'::text, 3200::numeric, null::numeric, 15::int, 'in_stock'::text, '{"Ports":"8-Port"}'::jsonb, 0::int),
  ('network-switch'::text, '16-Port'::text, 'NET-SW-16PORT'::text, 7800::numeric, null::numeric, 9::int, 'in_stock'::text, '{"Ports":"16-Port"}'::jsonb, 1::int),
  ('network-switch'::text, '24-Port'::text, 'NET-SW-24PORT'::text, 14500::numeric, null::numeric, 5::int, 'in_stock'::text, '{"Ports":"24-Port"}'::jsonb, 2::int),
  ('wireless-access-point'::text, 'Ceiling Mount AC1200'::text, 'NET-AP-CEILINGMOUNTAC'::text, 7900::numeric, null::numeric, 8::int, 'in_stock'::text, '{"Type":"Ceiling Mount AC1200"}'::jsonb, 0::int),
  ('wireless-access-point'::text, 'Outdoor 5GHz'::text, 'NET-AP-OUTDOOR5GHZ'::text, 6800::numeric, null::numeric, 6::int, 'in_stock'::text, '{"Type":"Outdoor 5GHz"}'::jsonb, 1::int),
  ('monocrystalline-solar-panel'::text, '100 Watts'::text, 'SOL-PNL-100WATTS'::text, 8500::numeric, null::numeric, 20::int, 'in_stock'::text, '{"Power":"100 Watts"}'::jsonb, 0::int),
  ('monocrystalline-solar-panel'::text, '200 Watts'::text, 'SOL-PNL-200WATTS'::text, 15500::numeric, null::numeric, 16::int, 'in_stock'::text, '{"Power":"200 Watts"}'::jsonb, 1::int),
  ('monocrystalline-solar-panel'::text, '330 Watts'::text, 'SOL-PNL-330WATTS'::text, 24500::numeric, 27000::numeric, 10::int, 'in_stock'::text, '{"Power":"330 Watts"}'::jsonb, 2::int),
  ('monocrystalline-solar-panel'::text, '550 Watts'::text, 'SOL-PNL-550WATTS'::text, 36000::numeric, null::numeric, 6::int, 'in_stock'::text, '{"Power":"550 Watts"}'::jsonb, 3::int),
  ('solar-charge-controller'::text, '30A PWM'::text, 'SOL-CC-30APWM'::text, 3800::numeric, null::numeric, 18::int, 'in_stock'::text, '{"Rating":"30A PWM"}'::jsonb, 0::int),
  ('solar-charge-controller'::text, '60A MPPT'::text, 'SOL-CC-60AMPPT'::text, 14500::numeric, 15900::numeric, 7::int, 'in_stock'::text, '{"Rating":"60A MPPT"}'::jsonb, 1::int),
  ('solar-cable-mc4-kit'::text, '10 Metres'::text, 'SOL-CBL-10METRES'::text, 2800::numeric, null::numeric, 25::int, 'in_stock'::text, '{"Length":"10 Metres"}'::jsonb, 0::int),
  ('solar-cable-mc4-kit'::text, '20 Metres'::text, 'SOL-CBL-20METRES'::text, 4800::numeric, null::numeric, 16::int, 'in_stock'::text, '{"Length":"20 Metres"}'::jsonb, 1::int),
  ('solar-cable-mc4-kit'::text, '50 Metres'::text, 'SOL-CBL-50METRES'::text, 10500::numeric, null::numeric, 6::int, 'in_stock'::text, '{"Length":"50 Metres"}'::jsonb, 2::int),
  ('deep-cycle-solar-battery'::text, '100Ah'::text, 'BAT-DC-100AH'::text, 18500::numeric, null::numeric, 14::int, 'in_stock'::text, '{"Capacity":"100Ah"}'::jsonb, 0::int),
  ('deep-cycle-solar-battery'::text, '150Ah'::text, 'BAT-DC-150AH'::text, 26500::numeric, 29000::numeric, 9::int, 'in_stock'::text, '{"Capacity":"150Ah"}'::jsonb, 1::int),
  ('deep-cycle-solar-battery'::text, '200Ah'::text, 'BAT-DC-200AH'::text, 33500::numeric, null::numeric, 7::int, 'in_stock'::text, '{"Capacity":"200Ah"}'::jsonb, 2::int),
  ('hybrid-solar-inverter'::text, '1 kVA / 12V'::text, 'INV-HYB-1KVA12V'::text, 14500::numeric, null::numeric, 9::int, 'in_stock'::text, '{"Rating":"1 kVA / 12V"}'::jsonb, 0::int),
  ('hybrid-solar-inverter'::text, '3 kVA / 24V'::text, 'INV-HYB-3KVA24V'::text, 38500::numeric, 42000::numeric, 6::int, 'in_stock'::text, '{"Rating":"3 kVA / 24V"}'::jsonb, 1::int),
  ('hybrid-solar-inverter'::text, '5 kVA / 48V'::text, 'INV-HYB-5KVA48V'::text, 78000::numeric, null::numeric, 3::int, 'in_stock'::text, '{"Rating":"5 kVA / 48V"}'::jsonb, 2::int),
  ('surface-water-pump'::text, '0.5 HP'::text, 'PMP-SRF-05HP'::text, 7500::numeric, null::numeric, 12::int, 'in_stock'::text, '{"Power":"0.5 HP"}'::jsonb, 0::int),
  ('surface-water-pump'::text, '1 HP'::text, 'PMP-SRF-1HP'::text, 11800::numeric, 12900::numeric, 10::int, 'in_stock'::text, '{"Power":"1 HP"}'::jsonb, 1::int),
  ('surface-water-pump'::text, '1.5 HP'::text, 'PMP-SRF-15HP'::text, 16500::numeric, null::numeric, 6::int, 'in_stock'::text, '{"Power":"1.5 HP"}'::jsonb, 2::int),
  ('pressure-booster-pump'::text, '0.75 HP'::text, 'PMP-BST-075HP'::text, 14500::numeric, null::numeric, 8::int, 'in_stock'::text, '{"Power":"0.75 HP"}'::jsonb, 0::int),
  ('pressure-booster-pump'::text, '1 HP'::text, 'PMP-BST-1HP'::text, 18900::numeric, null::numeric, 6::int, 'in_stock'::text, '{"Power":"1 HP"}'::jsonb, 1::int),
  ('pressure-booster-pump'::text, '1.5 HP'::text, 'PMP-BST-15HP'::text, 24500::numeric, null::numeric, 4::int, 'in_stock'::text, '{"Power":"1.5 HP"}'::jsonb, 2::int),
  ('borehole-submersible-pump'::text, '0.75 HP'::text, 'PMP-SUB-075HP'::text, 21500::numeric, null::numeric, 5::int, 'in_stock'::text, '{"Power":"0.75 HP"}'::jsonb, 0::int),
  ('borehole-submersible-pump'::text, '1 HP'::text, 'PMP-SUB-1HP'::text, 26500::numeric, null::numeric, 5::int, 'in_stock'::text, '{"Power":"1 HP"}'::jsonb, 1::int),
  ('borehole-submersible-pump'::text, '2 HP'::text, 'PMP-SUB-2HP'::text, 44000::numeric, 47500::numeric, 2::int, 'in_stock'::text, '{"Power":"2 HP"}'::jsonb, 2::int),
  ('petrol-generator'::text, '2.5 kVA'::text, 'PWR-GEN-25KVA'::text, 38500::numeric, 42000::numeric, 6::int, 'in_stock'::text, '{"Output":"2.5 kVA"}'::jsonb, 0::int),
  ('petrol-generator'::text, '5 kVA'::text, 'PWR-GEN-5KVA'::text, 79000::numeric, null::numeric, 4::int, 'in_stock'::text, '{"Output":"5 kVA"}'::jsonb, 1::int),
  ('petrol-generator'::text, '7.5 kVA'::text, 'PWR-GEN-75KVA'::text, 125000::numeric, null::numeric, 2::int, 'in_stock'::text, '{"Output":"7.5 kVA"}'::jsonb, 2::int),
  ('automatic-voltage-regulator'::text, '1 kVA'::text, 'PWR-AVR-1KVA'::text, 4500::numeric, null::numeric, 14::int, 'in_stock'::text, '{"Rating":"1 kVA"}'::jsonb, 0::int),
  ('automatic-voltage-regulator'::text, '2 kVA'::text, 'PWR-AVR-2KVA'::text, 7200::numeric, null::numeric, 10::int, 'in_stock'::text, '{"Rating":"2 kVA"}'::jsonb, 1::int),
  ('automatic-voltage-regulator'::text, '5 kVA'::text, 'PWR-AVR-5KVA'::text, 14800::numeric, null::numeric, 5::int, 'in_stock'::text, '{"Rating":"5 kVA"}'::jsonb, 2::int),
  ('power-bank'::text, '10,000 mAh'::text, 'ELC-PB-10000MAH'::text, 1800::numeric, null::numeric, 30::int, 'in_stock'::text, '{"Capacity":"10,000 mAh"}'::jsonb, 0::int),
  ('power-bank'::text, '20,000 mAh'::text, 'ELC-PB-20000MAH'::text, 3200::numeric, 3600::numeric, 22::int, 'in_stock'::text, '{"Capacity":"20,000 mAh"}'::jsonb, 1::int),
  ('wireless-earbuds'::text, 'Standard'::text, 'ELC-EB-STANDARD'::text, 2500::numeric, 3200::numeric, 40::int, 'in_stock'::text, '{"Model":"Standard"}'::jsonb, 0::int),
  ('surge-protected-extension-socket'::text, '4-Way'::text, 'ACC-EXT-4WAY'::text, 900::numeric, null::numeric, 50::int, 'in_stock'::text, '{"Sockets":"4-Way"}'::jsonb, 0::int),
  ('surge-protected-extension-socket'::text, '6-Way'::text, 'ACC-EXT-6WAY'::text, 1300::numeric, null::numeric, 40::int, 'in_stock'::text, '{"Sockets":"6-Way"}'::jsonb, 1::int),
  ('surge-protected-extension-socket'::text, '8-Way'::text, 'ACC-EXT-8WAY'::text, 1800::numeric, null::numeric, 28::int, 'in_stock'::text, '{"Sockets":"8-Way"}'::jsonb, 2::int),
  ('tv-wall-mount-bracket'::text, '32 to 55 Inch'::text, 'ACC-WM-32TO55INCH'::text, 1500::numeric, null::numeric, 35::int, 'in_stock'::text, '{"Fits TV size":"32 to 55 Inch"}'::jsonb, 0::int),
  ('tv-wall-mount-bracket'::text, '55 to 85 Inch'::text, 'ACC-WM-55TO85INCH'::text, 2600::numeric, null::numeric, 20::int, 'in_stock'::text, '{"Fits TV size":"55 to 85 Inch"}'::jsonb, 1::int)
) as v(product_slug, label, sku, price, previous_price, stock, availability, specs, sort_order)
join public.products p on p.slug = v.product_slug
on conflict (sku) do nothing;
